# Site settings
email: hjvsdh.dev@gmail.com
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-120591017-1

# SEO settings
title: 개발새발 블로그
description: Python, Django, React 등 이런저런 개발 그리고 잡다한 생각을 적을거에요.
url: ""
twitter_username: DirtyBackend
default_img: 

# Profile settings
name: dohyun
profile_img: 
profile: 
social:
  github: 

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown

permalink: /:year/:month/:day/:title/

# Sass
sass:
  sass_dir: _sass
  style: compressed

kramdown:
  parse_block_html: true
highlighter: rouge
# Gems
plugins: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
